apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
  labels:
    run: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hello-node
    spec:
      containers:
        - image: gcr.io/unity-ml-avilay-sandbox-test/hello-node:v1
          name: hello-node
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
