apiVersion: v1
kind: PersistentVolume
metadata:
  name: mldata-disk
  namespace: learn-k8
spec:
  storageClassName: ""
  capacity:
    storage: 256G
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: data
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-mldata-disk
  namespace: learn-k8
spec:
  storageClassName: ""
  volumeName: mldata-disk
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 256G