# This will fail because persistent volumes have to be present in the same namespace as the pod.
apiVersion: v1
kind: Pod
metadata:
  name: use-tblogs-1
  namespace: default
spec:
  volumes:
    - name: tblogs-nfs-vol
      persistentVolumeClaim:
        claimName: claim-tblogs-nfs
  containers:
    - name: python-http-server
      image: python:latest
      command: ["python", "-m", "http.server"]
      volumeMounts:
        - mountPath: "/tblogs"
          name: tblogs-nfs-vol